substitutions:
  _APP_HOST: ""
  _FIREBASE_DATABASE_URL: ""
  _FIREBASE_PROJECT_ID: ""
  _NODE_ENV: ""

options:
  substitution_option: "ALLOW_LOOSE"

steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/spinapp-dev", "."]
    id: "Build the Spinapp container image"

    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/spinapp-dev"]
    id: "Push the container image to Container Registry"

  #  Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "beta",
        "run",
        "deploy",
        "spinapp-dev",
        "--image",
        "gcr.io/$PROJECT_ID/spinapp-dev",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--set-env-vars",
        "^::^FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL}::\
        FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}::\
        APP_HOST=${_APP_HOST}::\
        NODE_ENV=${_NODE_ENV}",
        "--quiet",
      ]
    id: "Deploy Spinapp container image to Cloud Run"

images:
  - gcr.io/$PROJECT_ID/spinapp-dev
