substitutions:
  _SHOPIFY_API_KEY: ""
  _REACT_APP_API_KEY: ""
  _SHOPIFY_API_SECRET_KEY: ""
  _SHOPIFY_API_VERSION: ""
  _FIREBASE_DATABASE_URL: ""
  _FIREBASE_PROJECT_ID: ""
  _APP_HOST: ""
  _APP_BILLING_CONFIRM_URL: ""
  _APP_TEST_CHARGE: ""
  _APP_WEBHOOKS_TOPICS: ""
  _APP_SCOPE: ""
  _NODE_ENV: ""

options:
  substitution_option: "ALLOW_LOOSE"

steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/turtle-dev", "."]
    id: "Build the Turtle container image"

    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/turtle-dev"]
    id: "Push the container image to Container Registry"

  #  Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "beta",
        "run",
        "deploy",
        "turtle-dev",
        "--image",
        "gcr.io/$PROJECT_ID/turtle-dev",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--set-env-vars",
        "^::^SHOPIFY_API_KEY=${_SHOPIFY_API_KEY}::\
        REACT_APP_API_KEY=${_REACT_APP_API_KEY}::\
        SHOPIFY_API_SECRET_KEY=${_SHOPIFY_API_SECRET_KEY}::\
        SHOPIFY_API_VERSION=${_SHOPIFY_API_VERSION}::\
        FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL}::\
        FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}::\
        APP_HOST=${_APP_HOST}::\
        APP_SCOPE=${_APP_SCOPE}::\
        APP_BILLING_CONFIRM_URL=${_APP_BILLING_CONFIRM_URL}::\
        APP_TEST_CHARGE=${_APP_TEST_CHARGE}::\
        APP_WEBHOOKS_TOPICS=${_APP_WEBHOOKS_TOPICS}::\
        NODE_ENV=${_NODE_ENV}",
        "--quiet",
      ]
    id: "Deploy Turtle container image to Cloud Run"

images:
  - gcr.io/$PROJECT_ID/turtle-dev
