#!/bin/bash

echo "SHOPIFY_API_KEY=$SHOPIFY_API_KEY" > .env
echo "SHOPIFY_API_SECRET_KEY=$SHOPIFY_API_SECRET_KEY" >> .env
echo "SHOPIFY_API_VERSION=$SHOPIFY_API_VERSION" >> .env
echo "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" >> .env
echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
echo "APP_HOST=$APP_HOST" >> .env
echo "APP_BILLING_CONFIRM_URL=$APP_BILLING_CONFIRM_URL" >> .env
echo "APP_TEST_CHARGE=$APP_TEST_CHARGE" >> .env
echo "APP_WEBHOOKS_TOPICS=$APP_WEBHOOKS_TOPICS" >> .env
echo "APP_SCOPE=$APP_SCOPE" >> .env
echo "NODE_ENV=$NODE_ENV" >> .env

npm run start